const express = require('express')
const dotenv = require('dotenv').config({ path: 'backend/.env'})
const dbConnection = require('./configuration/db')
const countryRoute = require('./routes/countryRoute')
const adminRoute=require('./routes/adminRoutes')
const {errorHandler}=require('./middleware/errorMiddleWare')
port = process.env.PORT || 5000
dbConnection()
const app = express()
app.use(express.json())
app.use(express.urlencoded({ extended: false}))
app.use('/getCountry',countryRoute)
app.use('/addUser',adminRoute)
app.use(errorHandler)
app.listen(port, () => console.log(`server started on ${port}`))